### ISSUE TITLE
M1 issue

### ISSUE THREAD

**Issue by marcstein** [elbywan/moongoon#11]
Hi,

When I attempt to include moongoon on an M1 Mac running 11.5.2 I get the attached error.
[error.txt](https://github.com/elbywan/moongoon/files/7047573/error.txt)

Same code runs fine on Ubuntu. I've tried reinstalling gmp through Brew and am running the latest version.

Same code without Moongoon compiles with no issue.

Thanks!

Marc

**Comment by elbywan** [comment]
Hey @marcstein,

> When I attempt to include moongoon on an M1 Mac running 11.5.2 I get the attached error.

Sorry, I will be unable to reproduce since I don't have access to an M1 mac myself.

But since the issue is not specific to Moongoon as it comes from `BigInt` usage of `libgmp`, you could ask directly in the [crystal forum](https://forum.crystal-lang.org/) or [gitter](https://gitter.im/crystal-lang/crystal). I think there are some people that were successful in running crystal with an M1 mac already.

**Comment by marcstein** [comment]
Thanks, Julien.

I'm currently running Crystal on the M1, it's just the attempt to load
Moongoon that throws the error in compilation. I thought that you might
have encountered this before, but no worries.

Best,

Marc

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. ***@***.***
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by marzhaev** [comment]
Hi,

Just an idea to throw in. To me it looks like you have Intel and M1 messed up. The chances are your Crystal binary is for x86 and brew is arm64. Either try to dig in or set the stack from scratch.

General guidance for all-M1-in is available here - https://maxfierke.com/blog/posts/so-you-want-to-compile-crystal-on-arm64-macos

**Comment by marcstein** [comment]
Excellent suggestion! I'll try reinstalling from scratch.

Thanks!

Marc
Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. ***@***.***
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>
